### ISSUE TITLE
lists seem to be formatted wrong

### ISSUE THREAD

**Issue by igalic** [paulrouget/dzslides#125]
currently, the CSS looks like:

```css
  ul, ol {
      margin: 40px 100px 0 100px;
  }
  li > ul, ol {
      margin: 0 0 15px 50px;
      list-style-image: none; /* in case parent list has some */
  }
```

This doesn't appear to be working: `li > ul, ol` needs to be reversed.
